security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    api:
      pattern: ^/api
      stateless: true
      provider: app_user_provider
      custom_authenticator: App\Security\ApiTokenAuthenticator

    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\AppUserAuthenticator
      logout:
        path: app_logout
        target: app_login

  access_control:
    - { path: ^/main, roles: ROLE_USER }
    # - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    # - { path: ^/api, roles: ROLE_USER } 

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
